# 사이트 설정 파일 (config 파일)
#
# 테마 지정
theme: jekyll-theme-chirpy

# 사이트 언어 설정 (예: 'ko'로 변경 시 한글로 표시)
# 만약 '_data/locales' 폴더에 해당 언어 파일이 있으면 레이아웃 언어도 변경됨
lang: ko # → 'ko'로 변경 추천

# 사이트 시간대 설정 (https://kevinnovak.github.io/Time-Zone-Picker 참고)
timezone: Asia/Seoul

# jekyll-seo-tag 설정 (검색엔진 최적화 메타 태그)
# ↓ --------------------------

title: Developro # 사이트의 메인 제목  ← 수정이 필요한 곳 (사이트 이름으로)
tagline: 개발자 Developro 입니다 # 사이트 부제목    ← 수정이 필요한 곳 (원하는 부제목)
description: >- # SEO 메타와 atom 피드에 사용됨
  A minimal, responsive and feature-rich Jekyll theme for technical writing.  # ← 사이트 설명

# 사이트의 프로토콜 및 호스트명 입력 (예: 'https://username.github.io', 마지막에 '/' 없이)
url: "https://aoperat.github.io" # ← 수정이 필요한 곳 (본인 주소)

github:
  username: aoperat # 본인 GitHub 사용자명으로 변경   ← 수정이 필요한 곳

# twitter:
#   username: aoperat # 본인 트위터 사용자명으로 변경 ← 수정이 필요한 곳

social:
  # 전체 이름으로 변경 (글 작성자 및 푸터 저작권자에 표시됨)
  name: Developro # ← 본인 이름으로 변경
  email: aoperat@gmail.com # 본인 이메일로 변경   ← 수정이 필요한 곳
  links:
    # 첫 번째 항목이 저작권자 링크로 사용됨
    # - https://twitter.com/aoperat # 본인 트위터 주소로 변경  ← 수정이 필요한 곳
    - https://github.com/aoperat # 본인 깃허브 주소로 변경 ← 수정이 필요한 곳
    # 아래는 추가 소셜 링크 (필요시 주석 해제하여 사용)
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# 사이트 검증 코드 입력 (각 서비스별 코드 입력)
webmaster_verifications:
  google: # 구글 사이트 인증 코드 입력
  bing: # Bing 인증 코드 입력
  alexa: # Alexa 인증 코드 입력
  yandex: # Yandex 인증 코드 입력
  baidu: # Baidu 인증 코드 입력
  facebook: # Facebook 인증 코드 입력

# ↑ --------------------------
# jekyll-seo-tag 설정 끝

# 웹 분석(트래픽 측정) 도구 설정
analytics:
  google:
    id: G-XF9H5LNT7T # 구글 애널리틱스 ID 입력
  goatcounter:
    id: # GoatCounter ID 입력
  umami:
    id: # Umami ID 입력
    domain: # Umami 도메인 입력
  matomo:
    id: # Matomo ID 입력
    domain: # Matomo 도메인 입력
  cloudflare:
    id: # Cloudflare Web Analytics 토큰 입력
  fathom:
    id: # Fathom 사이트 ID 입력

# 페이지 뷰 설정 (현재 'goatcounter'만 지원)
pageviews:
  provider:

# 색상 테마 선호도 설정
#
# 비워두면 시스템 기본값(다크/라이트)을 따르고,
# 사이드바 좌하단에서 테마(다크/라이트) 변경 버튼 제공
#
# 사용 가능한 옵션:
#   light — 밝은 테마 사용
#   dark — 어두운 테마 사용
#
theme_mode:

# 미디어 리소스(CDN) 엔드포인트
# 지정하면, 모든 미디어 리소스(아바타, 이미지, 오디오, 비디오)의 경로 앞에 자동으로 CDN 주소가 붙음
# 예: 'https://cdn.com'
cdn:

# 사이드바 아바타 (로컬 또는 CORS 리소스 사용 가능)
avatar: /assets/img/favicons/logo-192x192.png

# SEO og:image 태그에 사용될 사이트 전체 미리보기 이미지 URL
# 각 페이지 front matter의 'image'로 덮어쓸 수 있음
social_preview_image:

# 본문에서 TOC(목차) 표시 전체 설정
toc: true

comments:
  # 전체 댓글 기능 설정 (비워두면 비활성화)
  provider: # [disqus | utterances | giscus]
  # 각 댓글 제공업체별 상세 설정
  disqus:
    shortname: # Disqus 단축이름 입력
  utterances:
    repo: # <깃허브 사용자명>/<저장소명>
    issue_term: # <url | pathname | title | ...>
  giscus:
    repo: # <깃허브 사용자명>/<저장소명>
    repo_id:
    category:
    category_id:
    mapping: # 옵션, 기본값 'pathname'
    strict: # 옵션, 기본값 '0'
    input_position: # 옵션, 기본값 'bottom'
    lang: # 옵션, 기본값 site.lang 값
    reactions_enabled: # 옵션, 기본값 '1'

# 정적 자산 직접 호스팅 설정 (선택사항)
assets:
  self_host:
    enabled: # true/false, 비워두면 false
    env: # 적용할 Jekyll 환경 (development/production), 비워두면 둘 다

pwa:
  enabled: true # PWA 기능 사용(설치 가능)
  cache:
    enabled: true # 오프라인 캐시 기능 사용
    # 아래에 지정한 경로들은 PWA 캐시에 포함하지 않음 (예: 같은 도메인 내 다른 사이트의 baseurl)
    deny_paths:
      # - "/example"  # "/example/*" 주소는 캐시에서 제외됨

# 한 페이지에 보여줄 게시물 수
paginate: 10

# 사이트의 기본 URL (baseurl)
baseurl: ""

plugins:
  - jekyll-sitemap
  - jekyll-feed



# ------------ 아래 옵션들은 특별히 필요하지 않으면 수정하지 않는 것을 권장 ------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # 빈 문자열: 프로젝트 내 모든 파일 적용
      type: posts
    values:
      layout: post
      comments: true # 게시글에 댓글 기능 활성화
      toc: true # 게시글에 목차 표시
      # 아래 permalink 옵션은 모든 게시글 링크 구조를 통일하므로, 특별한 경우 외에는 수정 금지
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # 위 collections의 tabs 참고
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
